services:
  builder:
    image: mir-toy/build
    build:
      context: .
      dockerfile: build.container
    volumes:
      - ../:/src
      - ../build/deb/:/build
      - ../build/deps:/deps
    command: |
      bash -c '
      CC=gcc-14 CXX=g++-14 cmake -B /build -S /src/ -DFETCH_TARGET_DIR=/deps

      cd /build
      cmake --build .

      cpack -G DEB
      '
