services:
  builder:
    image: mir-toy/build
    build:
      context: .
      dockerfile: build.container
    volumes:
      - ../:/src
      - ../build/deb/:/build
      - ../build/deps:/deps
    command: |
      bash -c '
      update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 99
      update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-14 99
      update-alternatives --get-selections
      g++ --version

      cmake -B /build -S /src/ -DFETCH_TARGET_DIR=/deps

      cd /build
      cmake --build .

      cpack -G DEB
      '
